Лабораторная работа №3
Programming-Classrooms/practicalworks-IvannDegtyarenko pull request #4
Opened 2023-12-01 21:30 UTC by IvannDegtyarenko

## Pull Request лабораторной работы №3

### Условие лабраторной работы

Вариант 32.
В массиве, состоящем из n целых элементов, вычислить:
- сумму элементов массива с нечетными номерами;
- произведение элементов массива, расположенных между первым и последним 
положительными элементами.
Сжать массив, удалив из него все элементы, модуль которых больше числа N.
Освободившиеся в конце массива элементы заполнить нулями.

### Вопросы по условию

Отсутствуют

2023-12-02 06:46 UTC, AlexandrOsiptsov requested changes
Есть над чем работать. Внимательно читай комменты и вдумывайся в назначение своих функций

2023-12-02 06:46 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3.cpp
> +		i += 2;
Шаг итератора прописывается после условия завершения. Т.е.:
```cpp
for(size_t i = 0; i < size; i += 2) { ... }
```

2023-12-02 06:46 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3.cpp
> +int firstPositive(int32_t* arr, const size_t arraySize)
`arraySize` лучше передавать по ссылке

2023-12-02 06:46 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3.cpp
> +	if (firstPositiveDigit == -1) {
Задача твоей функции - найти индекс первого положительного. В случае отсутствия такого обычно возвращают несуществующий индекс, т.е. -1.
Исключения выбрасываются при невозможности дальнейшей работы, ошибки переданных аргументов, но не в таком случае. Просто возвращай -1

2023-12-02 06:46 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3.cpp
> +int lastPositive(int32_t* arr, const size_t arraySize)
Аналогично

2023-12-02 06:46 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3.cpp
> +		throw std::exception("The second positive value is missing!");
Аналогично

2023-12-02 06:46 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3.cpp
> +void multiplicationOfElements(int32_t* arr, const size_t arraySize)
Снова по ссылке. + подумай над более коротким названием функции

2023-12-02 06:46 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3.cpp
> +	std::cout << "\nMultiplication of elements between the first and last positive number = " << multiplication;
Вывод в консоль из функции не делается, если функция по умолчанию этого не предполагает. Название функции не отражает её назначения.
В этом случае тебе лучше написать функцию под более общий случай. К примеру, которая на вход принимает два индекса, массив, возвращает произведение элементов между индексами. А потом уже использовать это в main.

2023-12-02 06:46 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3.cpp
> +		try {
Плохая практика. Еслм ты всё равно завершаешь работу программы, то зачем пишешь эту обработку внутри другого try-catch блока?

2023-12-02 09:06 UTC, IvannDegtyarenko commented
Вот исправляющий коммит: 634411c6b53135da3f081064551cace3f94c5075

2023-12-15 21:59 UTC, AlexandrOsiptsov requested changes
По оформлению вопросов нет. С. названиями снова беда. Лабу нужно проверять на работоспособность перед сдачей. И при внесении изменений, изменяй старые файлы, а не добавляй новые

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +	else {
Нет смысла ставить оператор `else` после `throw`, так как в случае выполнения условия в `if()` ты всё равно не дойдёшь до кода после выброса исключения

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +		}
Лучше заставь юзера вводить значение, пока не введёт валидное

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +void getRandomNumber(int32_t* arr, const size_t* arraySize)
Что здесь вообще происходит?
- Название функции говорит о том, что она возвращает случайное число. Тогда почему тип void? Почему в неё передаётся массив с размером?
- Ты передаёшь **константный указатель**, названный как `arraySize`. Понимаешь ли, что делаешь?

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +	}
А вот как раз для выполнения этого действия (получения случайного числа из интервала) и нужно было написать функцию 
```cpp
int32_t getRandInt(const int32_t& min, const int32_t& max)
```

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +	for (size_t i = 0; i < arraySize; ++i) {
Ну это уже просто абсурд. Ты заливаешь нерабочий код. Если `arraySize` - это указатель, то подумай о том, что будет, если это запустить

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +	}
Где `default`?  Даже если ты до этого исключил другие случаи, это не даёт тебе возможности нарушать стандарты кода

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +}
Уже говорилось про слово print.
Снова нерабочий код.

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +}
<img width="902" alt="image" src="https://github.com/Programming-Classrooms/practicalworks-IvannDegtyarenko/assets/105939033/57a73ab6-79a9-4b5f-b4cd-f26a99830699">

Как видишь, этот код не просто сломается во время выполнения, он даже не скомпилируется. Перед тем, как заливать лабу, обязательно проверяй её на работоспособность

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +		}
Неясно, к чему здесь ещё один вложенный `try-catch` блок

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +void sumOfTheElements(int32_t* arr, const size_t* arraySize)
Предлога **the** лучше избегать в названиях функций

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +	std::cout << "\nThe sum of the elements of the array with odd numbers = " << sum;
Функция должна выполнять только одну задачу. Здесь у тебя выполняется подсчёт суммы. Тогда пусть функция возвращает эту сумму, а выводить её на экран ты будешь уже при помощи кода в main

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +void arrayMinimizing(int32_t* arr, const size_t* arraySize)
Перепутал `*` с `&`

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +int lastPositive(int32_t* arr, const size_t* arraySize)
Перепутал `*` с `&`

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +int firstPositive(int32_t* arr, const size_t* arraySize)
Перепутал `*` с `&`

2023-12-15 21:59 UTC, AlexandrOsiptsov commented on laboratory-task-3/labwork3changed.cpp
> +void getInputType(int32_t* arr, const size_t* arraySize)
Перепутал `*` с `&`

2023-12-15 22:50 UTC, IvannDegtyarenko commented
Я не могу знать, как оказались в коммите первые две лабы, но здесь исправляющий коммит третьей лабы: a43a07197da54dffc569f6c8a028bebb213f1eec

2023-12-17 09:13 UTC, IvannDegtyarenko commented
Исправляющий коммит: 89dc7211d261b3f182e741fb3e9ab066416ce254

2024-01-06 19:10 UTC, AlexandrOsiptsov requested changes
Проблемы с написанием функций. Просмотри комменты

2024-01-06 19:10 UTC, AlexandrOsiptsov commented on laboratory-task-3/main.cpp
> +		arr[i] = rand() % (max - min + 1) + min;
Получение случайного числа из диапазона мы договаривались вписывать в отдельную функцию

2024-01-06 19:10 UTC, AlexandrOsiptsov commented on laboratory-task-3/main.cpp
> +}
По-хорошему разбить это на две функции.

2024-01-06 19:10 UTC, AlexandrOsiptsov commented on laboratory-task-3/main.cpp
> +
Во-первых, из названия вообще непонятно, что должна делать функция. Во-вторых, ты называешь переменную `lastPositiveDigit`, что переводится как "последняя положительная цифра". Хотя по факту, ты возвращаешь не саму цифру, а её индекс:

```cpp
if (arr[i] > 0 && i > lastPositiveDigit) {
	lastPositiveDigit = i;
}
```
Это должно быть отражено в названии. Например: `lastPosDigInd`

2024-01-06 19:10 UTC, AlexandrOsiptsov commented on laboratory-task-3/main.cpp
> +}
Почему бы просто не объявить результат умножения локально в теле функции, а потом возвратить его?

2024-01-06 19:10 UTC, AlexandrOsiptsov commented on laboratory-task-3/main.cpp
> +}
Что с названием? Minimizing в каком плане?

2024-01-06 19:10 UTC, AlexandrOsiptsov commented on laboratory-task-3/main.cpp
> +		printArray(arr, arraySize);
Логическое разделение

2024-01-06 19:12 UTC, AlexandrOsiptsov commented on laboratory-task-3/main.cpp
> +}
Тем более я уже тебе об этом писал в предыдущем ревью:

<img width="837" alt="image" src="https://github.com/Programming-Classrooms/practicalworks-IvannDegtyarenko/assets/105939033/fc3a489a-25c0-455b-a1ee-70fb314627eb">

2024-06-17 16:21 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:27 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:27 UTC, merged