Лабораторная работа №4
Programming-Classrooms/practicalworks-IvannDegtyarenko pull request #6
Opened 2023-12-02 10:34 UTC by IvannDegtyarenko

## Pull Request лабораторной работы №4

### Условие лабораторной работы

Вариант 2
В целочисленной квадратной матрице найти:
 - в первой строке первый нулевой элемент и столбец с этим элементом поменять местами с первым столбцом матрицы
- найти максимальный элемент верхнего правого треугольника полученной матрицы.

### Вопросы по условию

Отсутствуют

2023-12-02 21:44 UTC, AlexandrOsiptsov requested changes
Функциональная мания. Не нужно пытаться занести вообще весь код по функциям. В функции нужно заносить то, что является как бы универсальным и удобным. Исключительную логику конкретного задания (типа поменять местами минимальный право-лево-верхний элемент с нижней почкой номер 42) не нужно обрамлять в функции, т.к. нигде кроме этого места она использоваться точно не будет

2023-12-02 21:44 UTC, AlexandrOsiptsov commented on laboratory-task-4/labwork4.cpp
> +}
Беда с названием

2023-12-02 21:44 UTC, AlexandrOsiptsov commented on laboratory-task-4/labwork4.cpp
> +	if (inputType < 1 || inputType>2) {
Бинарные операторы выделяются пробелами

2023-12-02 21:44 UTC, AlexandrOsiptsov commented on laboratory-task-4/labwork4.cpp
> +		const size_t columns = getNumber();
А вот здесь ты правильно уловил суть функций. Как видишь в `getNumber()` нет никаких лишних выводов в консоль (такое встречалось у тебя в других лабах), поэтому ты можешь универсально её использовать

2023-12-02 21:44 UTC, AlexandrOsiptsov commented on laboratory-task-4/labwork4.cpp
> +}
Название беда. Здесь логика исключительно задания, функция далеко не универсальна, такие вещи можно не оформлять в виде функций. Если вынесешь это в `main`, то не будет выглядеть как-то плохо

2023-12-08 12:36 UTC, IvannDegtyarenko commented
Исправляющий коммит: fb1b6df7562044843926dd8c1eba0ad57051881d

2023-12-17 09:12 UTC, IvannDegtyarenko commented
Исправляющий коммит для четвертой лабы: eea13d4f87aa2628f871389a13bb9e468c5b9791

2024-01-12 22:12 UTC, AlexandrOsiptsov requested changes

2024-01-12 22:12 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +			mtrx[i][j] = rand() % (rightBoarder - leftBoarder + 1) + leftBoarder;
Ф-цию получения случайного числа из заданного диапазона пишем отдельно

2024-01-12 22:12 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +void fillingManually(int32_t**& mtrx, const size_t& columns, const size_t& rows)
&

2024-01-12 22:12 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +void fillingManually(int32_t**& mtrx, const size_t& columns, const size_t& rows)
fill*

2024-01-12 22:12 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +void matrixPrint(int32_t** mtrx, const size_t& columns, const size_t& rows)
mtrx rows cols

2024-01-12 22:12 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +	int64_t width = 5;
Пусть пользователь ф-ции будет иметь возможность сам определять ширину вывода. Аргумент по умолчанию

2024-01-12 22:12 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +	}
лучше убрать

2024-01-12 22:12 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +}
Лучше через возвращаемое значение

2024-01-12 22:12 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +	try {
Логическое разделение

2024-01-12 22:12 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +		std::cout << error.what();
`std::cerr`

2024-06-17 16:21 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:27 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:40 UTC, merged